version: '3'
services:
  web:
    build: .
    command: ["--port", "$PORT", "main:app", "--reload"]
    ports:
      - "8000:8000"
    volumes:
      - ./src:/data
    environment:
      PORT: 8000
      WORKERS: 4
      VERSION: 9.9.9
      CACHE: True
      CACHE_TYPE: redis
      CACHE_EXPIRATION: 120
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PYTHONUNBUFFERED: "TRUE"
    restart: always
  redis:
    image: "redis:6.0"
