---
name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-image:
    name: Test Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: e1himself/goss-installation-action@v1.0.3
      - name: Build Image
        run: docker build -t steamcmd/api:latest .
      - name: Test Image
        run: dgoss run steamcmd/api:latest

  python-lint:
    name: Python Lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.1.0
        with:
          # python files
          python-root-list: "src"
          # enabled linters
          use-black: true
          # disabled linters
          use-pylint: false
          use-pycodestyle: false
          use-flake8: false
          use-mypy: false
          use-isort: false
