---
name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-image:
    name: Test Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        run: docker build -t steamcmd/api:latest .

  python-lint:
    name: Python Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ricardochaves/python-lint@v1.3.0
        with:
          # python files
          python-root-list: "src"
          # enabled linters
          use-black: true
          # disabled linters
          use-pylint: false
          use-pycodestyle: false
          use-flake8: false
          use-mypy: false
          use-isort: false
